services:
  postgres:
    image: postgres:17-alpine
    container_name: shared-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - shared_postgres_data:/var/lib/postgresql/data
    networks:
      - private_chef_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" || exit 1',
        ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

volumes:
  shared_postgres_data:

networks:
  private_chef_network:
    name: private_chef_network
    driver: bridge
